apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
    - {{ .Values.storage.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.storageSize }}