version: "3.7"
services:
  user_db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  user_db: