apiVersion: v1
kind: ConfigMap
metadata:
  name: ice-cream-db-migrations
data: 
  {{ range $path, $a := .Files.Glob "migrations/**.sql" }}
  {{ base $path }}: {{ printf "%s" $a | toYaml }}
  {{ end }}
